# Use a slim version of the official Python 3.10 image
FROM python:3.10-slim

# Install required system packages for image processing (Pillow and OpenCV)
# C compiler required for some Python packages
 # Clean up to reduce image size
RUN apt-get update && apt-get install -y gcc libgl1 libglib2.0-0 && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy files
COPY api/ ./api/
COPY models/ ./models/
COPY shared/ ./shared/

# Expose port 8000 for FastAPI
EXPOSE 8000

# Default command to run the FastAPI server using uvicorn
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
